### ISSUE TITLE
Bump HybridAuth to latest stable release 2.12.0

### ISSUE THREAD

**Issue by edvincandon** [thelia-modules/TheliaHybridAuth#6]
Hey,

This is quite old but Facebook started using strict redirect url matching in their oAuth scheme (https://developers.facebook.com/blog/post/2017/12/18/strict-uri-matching/) -> the current version of TheliaHybridAuth isn't compliant.

All that is needed is to bump HybridAuth to 2.12.0 and ```composer require facebook/graph-sdk: "^5.4"```

I'd open a PR but I'm not sure how you'd want to handle this extra dependency since Thelia modules sometimes work out of the box without the need to use composer. 

Also I've only tested it for Facebook Login

**Comment by gillesbourgeat** [comment]
Thanks !
